### PR TITLE
Chiwetalu henry

### PR DESCRIPTION
**Pull request by dmoni042**
I made a clear change in the CONTRIBUTION.md

### CODE REVIEW

**Review by emaicorp — CHANGES_REQUESTED** [review]
The branches should be the contributors name not feature or refactoring or fix

**Comment by dmoni042** [comment]
The branch name is my name, Chiwetalu-henry

**Review by emaicorp — CHANGES_REQUESTED** [review]
You have made the requested changes for the contribution file connect with your co worker

**Comment by dmoni042** [comment]
She's aware of the changes or are you expecting me to add her name in my
branch?.

**Comment by emaicorp** [comment]
No just make the changes and push it

**Comment by dmoni042** [comment]
I've made the required changes.

**Review by emaicorp — APPROVED** [review]
You still had small changes but I will adjust it myself you did good

**Comment by dmoni042** [comment]
Much appreciated 001

**Pull request merged**
