### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by dpilot4ever**

### CODE REVIEW

**Review by emaicorp — CHANGES_REQUESTED** [review]
Firstly change the branching naming rules we said it should contain your name as the branch , now we don't have features or refactoring so don't add those in the commenting rules , also change the names to the proper repo base name

**Comment by dpilot4ever** [comment]
Thank you sir. Please sir can I rename my branch? I created a new branch
with my name when I did pull request, it gave me error that was what I
screenshot on the WhatsApp group.
Thank you sir.

**Comment by emaicorp** [comment]
You haven't made the changes as requested also yes you create a new branch and delete the old one

**Review by emaicorp — CHANGES_REQUESTED** [review]
You haven't made the requested changes also I can change your branch name and delete the old one

**Comment by dpilot4ever** [comment]
Thank you sir.

**Pull request merged**
