### PR TITLE
update config file

### PR DESCRIPTION
**Pull request by dpilot4ever**
Update in the config file

### CODE REVIEW

**Review by emaicorp — CHANGES_REQUESTED** [review]
You did good but you need to remove your env file from being added to the repo to avoid security risk apart from they everything looks ok also make sure to test your code before pushing so you don't break the code base

**Comment by dpilot4ever** [comment]
Thank you sir, i have done that as directed. Please  check if am doing the right thing. 
Thank you sir

**Review by emaicorp — COMMENTED** [review]
No dB config file

**Review by emaicorp — CHANGES_REQUESTED** [review]
No dB config file

**Comment by dpilot4ever** [comment]
Good afternoon Sir,
Thank you for your coaching skill. I am very grateful and pleased with your
coaching ability.
I have added the db.js again sir.
Warm regards.

**Review by emaicorp — APPROVED** [review]

**Comment by dpilot4ever** [comment]
Good day sir,
I have done that by git checkout to main, then git pull. i switched back to
branch Tremendous and did git pull too.
Please is there a way you can see  it to know if i am in other.
Thank you.
Warm regards

**Pull request merged**
